feat: UTF-8 HTTP Basic authentication (RFC-7617)
metricq/aiocouch pull request #47
Opened 2022-05-30 12:02 UTC by H--o-l

Username/password encoding in HTTP Basic authentication is broken for non-latin1
char.

UTF-8 Basic authentication is allowed since RFC-7617. Previously, RFC-2616
only allowed to use ISO-8859-1 text which is basically `latin1`.

CouchDB correctly encodes and decodes credentials using UTF-8:
https://github.com/apache/couchdb/blob/0059b8f90e58e10b199a4b768a06a762d12a30d3/dev/pbkdf2.py#L65

aiohttp still uses `latin1` as default:
https://github.com/aio-libs/aiohttp/blob/72d3d4b1f68cca5ad15ef50bffb0419b798c7f23/aiohttp/helpers.py#L139

aiocouch is made for CouchDB, and CouchDB follows RFC-7617, so I think
aiocouch should follow RFC-7617 too.

2022-05-30 12:13 UTC, adrienverge commented
I completely agree with this proposal.

For reference, I made an equivalent pull request on `couchdb-python`: https://github.com/djc/couchdb-python/issues/301

2022-05-30 14:32 UTC, bmario requested changes
Makes sense for me, but can you add a test with an UTF-8 user login. Thanks.

2022-05-31 07:07 UTC, H--o-l commented
(don't re-review my PR right now I'm working on adding the test)

2022-05-31 11:57 UTC, bmario requested changes
Thank you for your work, but I'm a bit confused now. Isn't the `§` character part of latin-1 and hence the test shouldn't fail even without the patch? As such, I'd like to see an obviously non-latin1 character, like emoji's.

2022-05-31 11:57 UTC, bmario commented on tests/test_connection.py
> +    assert doc.id == "org.couchdb.user:aiocouch_test_user_utf8"
I'd rather see this as another fixture akin to `couchdb_user_account` in `conftest.py`

2022-05-31 11:57 UTC, bmario commented on tests/test_connection.py
> +        user="aiocouch_test_user_utf8",
Can usernames be in UTF-8 as well? If so, I'd like to see an obviously non-latin1 character in the username.

2022-05-31 12:41 UTC, H--o-l commented
> Thank you for your work, but I'm a bit confused now. Isn't the `§` character part of latin-1 and hence the test shouldn't fail even without the patch? As such, I'd like to see an obviously non-latin1 character, like emoji's.

@bmario Indeed I should have checked latin-1 table directly and pick a char outside it.
The `§` fails with the code before this PR because his encoding is different in latin-1 than in UTF-8, see the following demonstration which use [the same code as aiohttp](https://github.com/aio-libs/aiohttp/blob/72d3d4b1f68cca5ad15ef50bffb0419b798c7f23/aiohttp/helpers.py#L192-L193):
```python
import base64
print(base64.b64encode('§'.encode('latin1')).decode('latin1'))  # pw==
print(base64.b64encode('§'.encode('utf-8')).decode('utf-8'))  # wqc=
```

I updated the PR to use the sofa emoji's 🛋️  (and with the other change you requested).

2022-05-31 12:46 UTC, bmario approved these changes
Looks good to me. Thank you.

2022-05-31 12:46 UTC, merged